export const SET_DEVICE_DIMENSIONS = 'SET_DEVICE_DIMENSIONS';
export const LOAD_NEURON_SELECTED = 'LOAD_NEURON_SELECTED';
export const LOAD_CONTENT_SELECTED = 'LOAD_CONTENT_SELECTED';
export const LOAD_USER_TREE = 'LOAD_USER_TREE';
export const AUTH_VALID = 'AUTH_VALID';
export const AUTH_NOTVALID = 'AUTH_NOTVALID';
export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';
