export const LANDSCAPE = 'LANDSCAPE';
export const PORTRAIT = 'PORTRAIT';
export const FLORECIDA = 'florecida';
export const CONTENT_TYPE_RECOMMENDED = 'recommended'
export const TIME_FOR_INACTIVITY = 12000;
export const URL_BASE = __DEV__ ? 'http://abi.shiriculapo.com' : 'http://abi.shiriculapo.com';
export const WEB_URL_BASE = __DEV__ ? 'http://aula.miaulabdp.com' : 'http://aula.miaulabdp.com';
export const CLOUDINARY_BASE = 'https://api.cloudinary.com';
export const ACHIEVEMENT_FINAL_QUIZ_NUMBER = 7;
